version: '3'
services:
  backend:
    build: backend
    ports:
      - 80:80
    networks:
      - my-network

  frontend:
    build: frontend
    ports:
      - 3000:3000
    networks:
      - my-network

  mongo:
    image: mongo
    volumes:
      - mongodb_data_container:/data/db
    ports:
      - 27017:27017
    networks:
      - my-network

volumes:
  mongodb_data_container:

networks:
  my-network:
