name: CI

on: [push, pull_request]

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        services:
            mongodb:
                image: mongo:4.4
                ports:
                    - 27017:27017

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Use Node.js 18
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Check folder location
              run: ls

            - name: Install backend dependencies
              run: cd backend-kelvin && npm ci

            - name: Install frontend dependencies
              run: cd frontend && npm ci

            - name: Install Playwright browsers
              run: npx playwright install --with-deps

            - name: Start backend server
              run: cd backend-kelvin && npm run start &
              env:
                  MONGO_URL: mongodb://localhost:27017

            - name: Start frontend server
              run: cd frontend && npm run start &

            - name: Run tests
              run: cd frontend/tests && npx playwright test
            - uses: actions/upload-artifact@v3
              if: always()
              with:
                  name: playwright-report
                  path: playwright-report/
                  retention-days: 30
