name: CI

on: [push, pull_request]

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        services:
            mongodb:
                image: mongo:4.4
                ports:
                    - 27017:27017

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Use Node.js 16.18.0
              uses: actions/setup-node@v2
              with:
                  node-version: 16.18.0

            - name: Check folder location
              run: ls

            - name: Install backend dependencies
              run: cd backend-orlando-pinero && npm ci

            - name: Install frontend dependencies
              run: cd frontend && npm ci

            - name: Start backend server
              run: cd backend-orlando-pinero && npm run start &
              env:
                  MONGO_URL: mongodb://localhost:27017

            - name: Start frontend server
              run: cd frontend && npm run start &

            - name: Run tests
              run: cd frontend/tests && npx playwright test
