name: CI

on: [push, pull_request]

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        container:
            image: mcr.microsoft.com/playwright:v1.33.0-jammy
            options: --ipc=host

        services:
            mongodb:
                image: mongo:4.4
                ports:
                    - 27017:27017

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Use Node.js 16
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: Check folder location
              run: ls

            - name: Install backend dependencies
              run: cd backend-kelvin && npm ci

            - name: Install frontend dependencies
              run: cd frontend && npm ci

            - name: Start backend server
              run: cd backend-kelvin && npm run start &
              env:
                  MONGO_URL: mongodb://localhost:27017

            - name: Test backend API reachability
              run: |
                  echo "Waiting for API to start..."
                  sleep 10 # Wait for the server to start
                  curl -i https://localhost:1026/api/authenticate

            - name: Start frontend server
              run: cd frontend && npm run start &

            - name: Print frontend server ip
              run: hostname -i

            - name: Wait for frontend server to start
              run: npx wait-on http://localhost:3000/

            - name: Run tests
              run: cd frontend/tests && npx playwright test

            - uses: actions/upload-artifact@v3
              if: always()
              with:
                  name: playwright-report
                  path: playwright-report/
                  retention-days: 30
